name: linux build
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17.7'
      - name: dependency for go
        run: sudo apt install libasound2-dev
      - name: setup dependencies
        run: go get
      - name: Build
        run: go build start.go
      - name: compress files
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '.gitignore, *.go, *.mod, *.sum, LICENSE.md, README.md, /*.github/*'
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: release.zip